# Production configuration - no secrets here!
# API keys loaded from environment variables
openai_api_key: ${OPENAI_API_KEY}
anthropic_api_key: ${ANTHROPIC_API_KEY}
perplexity_api_key: ${PERPLEXITY_API_KEY}

# Production settings
project_root: "./production_projects"
max_retries: 5
timeout: 60

# Production features
use_perplexity_app: false
enable_monitoring: true
enable_cost_alerts: true
max_budget_per_startup: 15.0  # $15 limit per startup

# Cost tracking (updated rates as of July 2024)
openai_input_cost_per_1k: 0.01
openai_output_cost_per_1k: 0.03
anthropic_input_cost_per_1k: 0.015
anthropic_output_cost_per_1k: 0.075
perplexity_cost_per_request: 0.005

# Security settings
log_level: "INFO"
max_concurrent_requests: 10
rate_limit_per_minute: 60

# Monitoring settings
metrics_port: 8000
health_check_port: 8001
log_rotation_size: "10MB"
log_retention_days: 30
