name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.1.4
        with:
          configurationFile: frontend/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: "debug"
          RENOVATE_AUTODISCOVER: "false"
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_PLATFORM: "github"
          RENOVATE_ONBOARDING: "false"
          RENOVATE_REQUIRE_CONFIG: "true"
          RENOVATE_BASE_BRANCHES: "main"
          RENOVATE_DEPENDENCY_DASHBOARD: "true"
          RENOVATE_DEPENDENCY_DASHBOARD_TITLE: "Dependencies Dashboard 📦"
          RENOVATE_EXTENDS: >-
            config:base,
            :dependencyDashboard,
            :semanticCommits,
            :semanticPrefixFix,
            :ignoreUnstable,
            :prNotPending,
            :updateNotScheduled,
            :automergeMinor,
            :automergePatch,
            :automergeTesters,
            :automergeTypes,
            group:allNonMajor
