name: Visual Regression Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  visual-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: npm run build-storybook

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && npm run test-visual"

      - name: Upload visual test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: visual-test-results
          path: |
            __image_snapshots__
            __diff_output__

      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const diffFiles = fs.readdirSync('__diff_output__');

            let comment = '### Visual Regression Test Results\n\n';
            comment += 'The following components have visual changes:\n\n';

            diffFiles.forEach(file => {
              comment += `- ${file.replace(/__diff_.*\.png$/, '')}\n`;
            });

            comment += '\nPlease review the changes in the artifacts.';

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
