version: "3.8"

services:
  # ... existing services ...

  email-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python -m app.worker.run_worker
    volumes:
      - ./backend:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/app
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=dev_secret_key
      - CORS_ORIGINS=["http://localhost:3000", "http://localhost:8000"]
      - SMTP_USER=${SMTP_USER:-neoforge@example.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-password}
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - app-network

  # ... existing networks and volumes ...
