# MVP Orchestrator Configuration
# Copy this to config.yaml and fill in your API keys

# API Keys (required)
openai_api_key: "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"
anthropic_api_key: "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"
perplexity_api_key: "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"

# Project Settings
project_root: "./mvp_projects"
max_retries: 3
timeout: 30

# Cost Tracking (update based on current pricing)
openai_input_cost_per_1k: 0.01
openai_output_cost_per_1k: 0.03
anthropic_input_cost_per_1k: 0.015
anthropic_output_cost_per_1k: 0.075
perplexity_cost_per_request: 0.005
