global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Rule files to load
rule_files:
  - "rules/*.yml"

# Scrape configurations
scrape_configs:
  # Main API service
  - job_name: "neoforge-api"
    scrape_interval: 10s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["api:8000"]

  # Node exporter for host metrics
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Redis exporter
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
